"use client";

import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import { Icon } from "@/components/icon";

export default function EnrollPage() {
  const [code, setCode] = useState("");
  const [deviceName, setDeviceName] = useState("iPhone");
  const [error, setError] = useState("");
  const [done, setDone] = useState(false);
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    const queryCode = new URLSearchParams(window.location.search).get("code");
    if (queryCode) setCode(queryCode);
  }, []);

  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    setError("");
    setLoading(true);
    try {
      const response = await fetch("/api/devices/enrollment/complete", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ code, deviceName }),
      });
      const data = await response.json();
      if (!response.ok) {
        setError(data.error ?? "That enrollment code could not be used.");
        return;
      }
      setDone(true);
    } catch {
      setError("The server could not be reached. Try again when connected to your private network.");
    } finally {
      setLoading(false);
    }
  }

  return (
    <main className="login-page">
      <section className="surface login-panel" aria-labelledby="enroll-title">
        <Link href="/" className="brand" aria-label="Finance Tracker home">
          <span className="brand-mark" aria-hidden="true" />
          <span className="brand-name">Finance Tracker<small>private ledger</small></span>
        </Link>
        {done ? (
          <>
            <h1 id="enroll-title">Phone authorized.</h1>
            <Link href="/mobile" className="button button-primary"><Icon name="plus" className="icon-sm" />Open Add</Link>
          </>
        ) : (
          <>
            <h1 id="enroll-title">Connect this phone.</h1>
            <p>Use the one-time code generated by the private admin workspace. It expires after 15 minutes.</p>
            <form className="login-form" onSubmit={submit}>
              <div className="field"><label htmlFor="enrollment-code">Enrollment code</label><input id="enrollment-code" className="input mono" value={code} onChange={(event) => setCode(event.target.value)} placeholder="A1B2C3D4E5" autoCapitalize="characters" required /></div>
              <div className="field"><label htmlFor="device-name">Device name</label><input id="device-name" className="input" value={deviceName} onChange={(event) => setDeviceName(event.target.value)} placeholder="iPhone" required /></div>
              {error ? <div className="form-error" role="alert">{error}</div> : null}
              <button className="button button-primary" type="submit" disabled={loading}><Icon name="smartphone" className="icon-sm" />{loading ? "Authorizing…" : "Authorize this phone"}</button>
            </form>
          </>
        )}
        <p className="login-footer"><Link href="/">Return to public preview</Link></p>
      </section>
    </main>
  );
}
